hydra:
  run:
    dir: output/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

experiment:
  project: "GPT_Max"
  run_name: "LM_Neo"

model:
  vocab_size: 32256  # cl100k_base vocab 100277, padded to multiple of 256 for tensor cores
  block_size: 4096
  n_embd: 4096
  n_layers: 24
  n_heads: 32
  n_kv_heads: 8
  
  # MoE Settings
  n_shared_experts: 2
  n_routed_experts: 24
  topk_experts: 8
  expert_hidden_size: 1024

data:
  train_data_root: "data/climbmix_400b/"
  val_data_root: "data/climbmix_400b/"

training:
  batch_size: 8
  grad_accum_steps: 8

  # Logistics
  logging_steps: 1
  checkpoint_interval: 8000
  generation_interval: 10000000
  eval_interval: 400
  eval_steps: 80
  eval_batch_size: 16
  eval_block_size: 2048
  
  # Optimization
  max_steps: 160000
  warmup_steps: 2000
  warmdown_ratio: 0.3   # last 30% of training: linear decay from max_lr to min_lr
  max_lr: 2.0e-4
  min_lr: 2.0e-5
  weight_decay: 0.1
  
# resume_checkpoint: output/checkpoints/LM_2/best_val