hydra:
  run:
    dir: output/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

experiment:
  project: "GPT_Max"
  run_name: "GatorLM2"

model:
  vocab_size: 129024        # DeepSeek V3 vocab size 128815, padded to multiple of 256
  block_size: 4096
  n_embd: 4096
  n_layers: 27
  n_heads: 16
  n_kv_heads: 4
  ffn_hidden_size: 5632     # 8/3 * n_embd (SwiGLU standard), rounded to multiple of 256

data:
  train_data_root: "data/climbmix_400b/"
  val_data_root: "data/climbmix_400b/"

training:
  # 3.5B params
  # Chinchilla-optimal: 20 tok/param -> ~70B tokens -> ~67,000 steps
  # tokens/step = batch(4) * grad_accum(16) * block(4096) * world(4 GPUs) = 1,048,576
  batch_size: 4
  grad_accum_steps: 16
  batch_warmup_steps: 1000

  # Logistics
  logging_steps: 100
  checkpoint_interval: 50000
  generation_interval: 10000000
  eval_interval: 1000
  eval_steps: 40
  eval_batch_size: 8
  eval_block_size: 4096

  # Optimization
  max_steps: 67000
  warmup_steps: 1000
  max_lr: 3.0e-4
  min_lr: 3.0e-5
  weight_decay: 0.1

# resume_checkpoint: output/checkpoints/LM_Basic_2B/best_val
